name: Android CMake

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Cache Android NDK
      uses: actions/cache@v4
      with:
        path: ~/android-ndk
        key: ndk-r26d

    - name: Download NDK
      run: |
        if [ ! -d "$HOME/android-ndk" ]; then
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip
          mv android-ndk-r26d $HOME/android-ndk
        fi

    - name: Configure
      run: |
        cmake -B build -S main/jni \
        -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE=$HOME/android-ndk/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-21

    - name: Build
      run: cmake --build build
