name: Android CMake Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release
  ANDROID_ABI: arm64-v8a
  ANDROID_PLATFORM: android-21

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ninja
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d

    - name: Configure CMake
      run: |
        cmake -B build \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=${{env.ANDROID_ABI}} \
        -DANDROID_PLATFORM=${{env.ANDROID_PLATFORM}}

    - name: Build
      run: cmake --build build

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build
